repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
#  - repo: https://github.com/cheshirekow/cmake-format-precommit
#    rev: v0.6.13
#    hooks:
#      - id: cmake-format
#      - id: cmake-lint
#  - repo: https://github.com/syntaqx/git-hooks
#    rev: v0.0.17
#    hooks:
#      - id: circleci-config-validate
#      - id: forbid-binary
#      - id: go-fmt
#      - id: go-test
#      - id: go-mod-tidy
#      - id: go-generate
#      - id: shellcheck
#      - id: shfmt
#  - repo: git://github.com/detailyang/pre-commit-shell
#    rev: 1.0.5
#    hooks:
#      - id: shell-lint
#        args: [--format=json]
#  - repo: https://github.com/comkieffer/pre-commit-xmllint.git
#    rev: 1.0.0
#    hooks:
#      - id: xmllint
#- repo: https://github.com/pre-commit/mirrors-scss-lint
#    rev: "v0.59.0"
#    hooks:
#      - id: scss-lint
#-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
#    rev: ${LATEST_SHA_OR_VERSION}
#    hooks:
#    - id: pretty-format-java-in-docker    # Useful to eventually SKIP pre-commit hooks
#      name: pretty-format-java-in-docker  # This is required, put something sensible
#      language: docker
#    - id: pretty-format-java
#      args: [--autofix]
#    - id: pretty-format-yaml
#      args: [--autofix, --indent, '2']
#  - repo: https://github.com/pre-commit/mirrors-prettier
#    rev: "" # Use the sha / tag you want to point at
#    hooks:
#      - id: prettier
#        additional_dependencies:
#          - prettier@2.1.2
#          - "@prettier/plugin-xml@0.12.0"
