---
name: "✅ Lynchee"

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"
  push:
    branches: [main]
    paths: [/public/arf.json]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          args: "--cache --max-cache-age 1d --config ./lychee.toml --insecure './public/arf.json'"
          format: markdown
          output: ./docs/LINKS_REPORT.md
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./docs/LINKS_REPORT.md
          labels: report, automated issue
